name: Java tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
      actions: write
      contents: read
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean verify --file pom.xml
    - name: Create Bug in azure
      uses: colindembovsky/az-create-work-item@v1.0.0
      with:
        token: ${{ secrets.PAT }}
        orgName: '01169567'
        project: 'SystemTestowy'
        type: User Story
        title: Work item from run ${{ github.run_number }}
        description: Created from Actions!
    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
  
