name: Java tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
      actions: write
      contents: read
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean verify --file pom.xml
    - name: Create azure devops issue if job failed
      uses: stefanstranger/azuredevops-bug-action@1.1
      if: failure()
      with:
        OrganizationName: "01169567"
        PAT: "PAT"
        ProjectName: "SystemTestowy"
        AreaPath: "SystemTestowy"
        IterationPath: "SystemTestowy"
        GithubToken: "GithubToken"
        WorkflowFileName: "maven.yml"
      env:
        PAT: ${{ secrets.PAT}}
        GithubToken: ${{secrets.GITHUB_TOKEN }}
    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
    - name: Create azure devops issue if job failed
      uses: stefanstranger/azuredevops-bug-action@1.1
      if: failure()
      with:
        OrganizationName: "01169567"
        PAT: "PAT"
        ProjectName: "SystemTestowy"
        AreaPath: "SystemTestowy"
        IterationPath: "SystemTestowy"
        GithubToken: "GithubToken"
        WorkflowFileName: "maven.yml"
      env:
        PAT: ${{ secrets.PAT}}
        GithubToken: ${{secrets.GITHUB_TOKEN }}
